name: Claude Review (Test)
on:
  issue_comment:
    types: [created]

jobs:
  review:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short diff
        run: |
          gh pr diff ${{ github.event.issue.number }} | head -n 200 > diff.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare request
        run: |
          jq -Rs . < diff.txt > diff.json
          cat > request.json <<EOF
          {
            "model": "claude-3-haiku-20240307",
            "max_tokens": 500,
            "messages": [
              {
                "role": "user",
                "content": "Проанализируй этот PR и предложи улучшения:\n$(cat diff.json)"
              }
            ]
          }
          EOF

      - name: Call Claude API
        run: |
          curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: ${{ secrets.CLAUDE_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d @request.json | tee api_response.json

          RESPONSE=$(jq -r '
            if .content and .content[0] and .content[0].text then
              .content[0].text
            elif .error and .error.message then
              "❌ Claude API error: " + .error.message
            else
              "❌ Claude не вернул ответа"
            end
          ' api_response.json)

          echo "$RESPONSE" > response.txt
          gh pr comment ${{ github.event.issue.number }} --body-file response.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
