name: Claude Review
on:
  issue_comment:
    types: [created]

jobs:
  review:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get available models
        run: |
          curl -s https://api.anthropic.com/v1/models \
            -H "x-api-key: ${{ secrets.CLAUDE_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" | jq -r '.data[].id' > models.txt

          echo "Доступные модели:"
          cat models.txt

          # Берём первую доступную модель
          MODEL=$(head -n 1 models.txt)
          echo "MODEL=$MODEL" >> $GITHUB_ENV

      - name: Get PR diff (limited)
        run: |
          gh pr diff ${{ github.event.issue.number }} | head -n 2000 > diff.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare request for Claude
        run: |
          jq -Rs . < diff.txt > diff.json

          cat > request.json <<EOF
          {
            "model": "${MODEL}",
            "max_tokens": 1000,
            "messages": [
              {
                "role": "user",
                "content": "Проанализируй этот PR и предложи улучшения:\n$(cat diff.json)"
              }
            ]
          }
          EOF

      - name: Call Claude API
        run: |
          curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: ${{ secrets.CLAUDE_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d @request.json | tee api_response.json

          RESPONSE=$(jq -r '.content[0].text // "❌ Claude не вернул ответа"' api_response.json)
          echo "$RESPONSE" > response.txt
          gh pr comment ${{ github.event.issue.number }} --body-file response.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
